import launch_ros.actions
from launch import LaunchDescription


def generate_launch_description():
    use_sim_time = {"use_sim_time": True}

    return LaunchDescription(
        [
            launch_ros.actions.Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                arguments=[
                    "--x",
                    "0",
                    "--y",
                    "0",
                    "--z",
                    "0",
                    "--qx",
                    "0",
                    "--qy",
                    "0",
                    "--qz",
                    "0",
                    "--qw",
                    "1",
                    "--frame-id",
                    "map",
                    "--child-frame-id",
                    "odom",
                ],
                parameters=[use_sim_time],
            ),
            launch_ros.actions.Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                arguments=[
                    "--x",
                    "0.12",
                    "--y",
                    "0.03",
                    "--z",
                    "0",
                    "--qx",
                    "0",
                    "--qy",
                    "0",
                    "--qz",
                    "0",
                    "--qw",
                    "1",
                    "--frame-id",
                    "base_link",
                    "--child-frame-id",
                    "camera_link",
                ],
                parameters=[use_sim_time],
            ),
            launch_ros.actions.Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                arguments=[
                    "--x",
                    "0",
                    "--y",
                    "0",
                    "--z",
                    "0",
                    "--qx",
                    "0",
                    "--qy",
                    "0",
                    "--qz",
                    "0",
                    "--qw",
                    "1",
                    "--frame-id",
                    "camera_link",
                    "--child-frame-id",
                    "x500_depth_0/OakD-Lite/base_link/StereoOV7251",
                ],
                parameters=[use_sim_time],
            ),
            launch_ros.actions.Node(
                package="ros_gz_bridge",
                executable="parameter_bridge",
                arguments=["/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock"],
                output="screen",
                parameters=[use_sim_time],
            ),
            launch_ros.actions.Node(
                package="ros_gz_bridge",
                executable="parameter_bridge",
                arguments=["/model/x500_depth_0/odometry@nav_msgs/msg/Odometry[gz.msgs.Odometry"],
                remappings=[("/model/x500_depth_0/odometry", "/odom")],
                output="screen",
                parameters=[use_sim_time],
            ),
            launch_ros.actions.Node(
                package="ros_gz_bridge",
                executable="parameter_bridge",
                arguments=["/depth_camera@sensor_msgs/msg/Image[gz.msgs.Image"],
                remappings=[("/depth_camera", "/camera/depth/image_raw")],
                output="screen",
                parameters=[use_sim_time],
            ),
            launch_ros.actions.Node(
                package="ros_gz_bridge",
                executable="parameter_bridge",
                arguments=["/camera_info@sensor_msgs/msg/CameraInfo[gz.msgs.CameraInfo"],
                remappings=[("/camera_info", "/camera/camera_info")],
                output="screen",
                parameters=[use_sim_time],
            ),
            launch_ros.actions.Node(
                package="ros_gz_bridge",
                executable="parameter_bridge",
                arguments=["/depth_camera/points@sensor_msgs/msg/PointCloud2[gz.msgs.PointCloudPacked"],
                remappings=[("/depth_camera/points", "/camera/depth/points")],
                output="screen",
                parameters=[
                    use_sim_time,
                    {
                        "qos_overrides./camera/depth/points.publisher.reliability": "best_effort",
                        "qos_overrides./camera/depth/points.publisher.history": "keep_last",
                        "qos_overrides./camera/depth/points.publisher.depth": 1,
                    },
                ],
            ),
        ]
    )
